name: Aldo Borrero
description: Thoughts about Android, NodeJS and technology in general
meta_description: "Thoughts about Android, NodeJS and technology in general"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
permalink: /archive/:year/:month/:day/:title/
domain_name: 'http://aldoborrero.com'
google_analytics: 'UA-25502409-2'

# Details for the RSS feed generator
url:            'http://aldoborrero.com'
author:         'Aldo Borrero'
